import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalNumbered } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Privacy Policy | ArticulateX",
  description: "How ArticulateX collects, uses, stores, and protects personal information.",
};

export default function PrivacyPolicyPage() {
  return (
    <LegalDocument
      title="Privacy Policy"
      updated="21 August 2026"
      intro="Articulate X respects your privacy and is committed to handling your personal data responsibly. This policy explains how we collect, use, store, process, and protect personal information when you visit articulatex.in, interact with our advertisements, submit an enquiry or assessment, register for a programme, purchase our services, participate in training, or otherwise interact with us."
      sections={[
        { title: "1. About Articulate X", body: <p>Articulate X is a professional education and training business focused on practical communication capabilities. Our programmes may include executive public speaking, business communication, executive presence, negotiation communication, presentation skills, structured communication frameworks, and related professional development training.</p> },
        { title: "2. Information We Collect", body: <><p>Depending on how you interact with us, we may collect:</p><LegalList items={["Full name, email address, telephone or mobile number", "Company, organisation, job title, professional background, and years of experience", "Areas of interest, training requirements, enquiries, assessments, surveys, and consultation information", "Billing and transaction information processed through payment providers", "Course submissions, assignments, feedback, responses, and communications", "IP address, browser and device type, operating system, approximate location, pages visited, referring campaign, cookies, and interaction data"]}/><p>Please provide information that is accurate and that you are authorised to provide.</p></> },
        { title: "3. Payments", body: <p>Payments may be processed by authorised third-party payment providers. Depending on the method, those providers may process card, bank, UPI, or other payment details. Articulate X generally does not store complete payment-card information when payment processing is handled by an authorised provider.</p> },
        { title: "4. Advertising and Lead Generation", body: <p>We may use Google, Meta, LinkedIn, and similar platforms. Depending on campaign configuration, we may receive information about an advertisement interaction, campaign source, lead-form submission, attributable website activity, or conversion.</p> },
        { title: "5. How We Use Personal Data", body: <LegalNumbered items={["Responding to enquiries and requests", "Providing information about programmes and services", "Conducting assessments and consultations", "Registering participants and delivering training", "Scheduling sessions and providing support", "Processing payments and maintaining records", "Sending administrative and permitted marketing communications", "Improving programmes and analysing website and campaign performance", "Measuring advertising effectiveness and preventing fraud or unauthorised access", "Maintaining business, tax, financial, and accounting records", "Complying with applicable law and protecting the rights, security, and legitimate interests of Articulate X and others"]}/> },
        { title: "6. Marketing Communications", body: <><p>Where permitted, we may contact you about programmes, workshops, assessments, events, training opportunities, corporate training, resources, offers, or promotions. You may opt out at any time using an unsubscribe mechanism or by contacting us. Opting out of marketing does not prevent important service communications.</p></> },
        { title: "7. Cookies and Similar Technologies", body: <p>We may use cookies, pixels, tags, analytics, advertising attribution, conversion tracking, retargeting, and similar technologies to operate and improve the website. You may control cookies through browser settings or controls made available on the website.</p> },
        { title: "8. Third-Party Providers", body: <p>We may use providers for hosting, cloud infrastructure, payments, email, CRM, analytics, advertising, scheduling, video conferencing, forms, assessments, messaging, and business administration. Providers may process information on our behalf or under their own policies, depending on the service.</p> },
        { title: "9. Sharing of Personal Data", body: <><p>We may share personal data where reasonably necessary with:</p><LegalList items={["Employees, representatives, trainers, coaches, facilitators, and contractors", "Payment, technology, infrastructure, CRM, communication, analytics, and advertising providers", "Professional advisers, auditors, accountants, and legal advisers", "Government authorities or law-enforcement agencies where legally required", "Successors or transaction parties in a merger, acquisition, restructuring, investment, sale, or transfer of assets"]}/><p>We do not sell personal data as a standalone commercial product.</p></> },
        { title: "10. Corporate Programmes", body: <p>Where an organisation provides participant information for programme administration, we may provide attendance, participation, completion, or aggregated feedback where appropriate. We will not disclose private participant information beyond what is reasonably necessary or agreed, subject to applicable law.</p> },
        { title: "11. Retention", body: <p>We retain personal data only as long as reasonably necessary for service delivery, business records, disputes, payments, accounting and tax requirements, legal obligations, security, agreements, and legitimate business needs. We may delete, anonymise, or dispose of information when it is no longer required.</p> },
        { title: "12. Security", body: <p>We use reasonable technical and organisational measures designed to protect personal data against unauthorised access, misuse, alteration, disclosure, loss, or destruction. No internet service or storage system can be guaranteed completely secure. You are responsible for protecting your account credentials.</p> },
        { title: "13. Your Rights", body: <><p>Subject to applicable law, you may request information about processing, correction, deletion where applicable, withdrawal of consent, or exercise of other data-protection rights. We may verify your identity before processing a request.</p></> },
        { title: "14. Children", body: <p>Our programmes are primarily designed for adults and working professionals. We do not knowingly seek to collect children’s personal data where prohibited by law. Contact us if you believe such information was provided improperly.</p> },
        { title: "15. International Processing", body: <p>Some providers may process or store information outside India. Where data is transferred or processed outside India, we seek to comply with applicable legal requirements.</p> },
        { title: "16. Third-Party Websites", body: <p>Our website or communications may link to third-party websites and services. Articulate X does not control their privacy practices. Review their policies before providing personal information.</p> },
        { title: "17. Changes", body: <p>We may update this policy to reflect changes to services, technology, business practices, or legal requirements. The updated version will be published with a revised date.</p> },
        { title: "18. Contact and Grievance", body: <><p>For questions, privacy requests, or concerns, contact:</p><p><strong>Articulate X</strong><br />Website: articulatex.in<br />Email: hello@articulatex.in<br />Privacy and grievance contact: hello@articulatex.in</p><p>Please use the subject line “Privacy Request” where appropriate.</p></> },
        { title: "19. Applicable Law", body: <p>This policy is intended to operate in accordance with applicable laws and regulations of India, including applicable data-protection and consumer-protection requirements. Mandatory legal rights will prevail where they differ from this policy.</p> },
      ]}
    />
  );
}
