import type { Metadata } from "next";
import { LegalDocument, LegalList, LegalNumbered } from "@/components/legal-document";

export const metadata: Metadata = {
  title: "Terms of Service | ArticulateX",
  description: "Terms governing access to ArticulateX programmes, courses, workshops, and services.",
};

export default function TermsOfServicePage() {
  return (
    <LegalDocument
      title="Terms of Service"
      updated="21 August 2026"
      intro="These Terms govern your access to and use of the Articulate X website, programmes, courses, workshops, assessments, training services, and related offerings. By accessing the website, submitting an enquiry, registering, purchasing a service, or participating in a programme, you agree to these Terms."
      sections={[
        { title: "1. About Articulate X", body: <p>Articulate X provides professional education and training services including executive public speaking, business communication, executive presence, presentation skills, negotiation communication, leadership communication, workshops, live training, corporate training, assessments, coaching, and related professional development.</p> },
        { title: "2. Eligibility", body: <><p>You must provide accurate information, have authority to register on behalf of an organisation where applicable, comply with these Terms, and use our services only for lawful purposes.</p></> },
        { title: "3. Registration and Enrolment", body: <p>Some programmes require an application, assessment, consultation, screening, or confirmation. An enquiry or application does not guarantee admission. A place is confirmed only after Articulate X communicates confirmation and, where applicable, payment is received.</p> },
        { title: "4. Programme Fees", body: <p>Fees are communicated before purchase or registration and may vary by duration, type, participation, scope, number of participants, customisation, promotions, and applicable taxes. Future pricing may change, but confirmed prices will not change retrospectively except as required by law or agreed.</p> },
        { title: "5. Payments", body: <p>Payments may be made through methods provided by Articulate X or authorised payment providers. A transaction is complete when the provider confirms successful payment. You must not use fraudulent methods or reverse legitimate transactions without first contacting us.</p> },
        { title: "6. Refunds and Cancellations", body: <><p>Refund eligibility depends on the programme and cancellation terms communicated at purchase. Unless programme-specific terms say otherwise:</p><LegalList items={["Cancellation requests should be submitted in writing", "Refunds are reviewed under applicable programme terms", "Substantially delivered sessions may not be refundable where permitted by law", "Non-recoverable processing charges may be deducted where permitted and disclosed", "Approved refunds are generally returned through the original payment method"]}/><p>Corporate or customised programmes may have separate terms. Nothing limits mandatory consumer rights.</p></> },
        { title: "7. Programme Schedule", body: <p>Articulate X may determine schedules, session times, trainers, facilitators, and delivery formats. We will make reasonable efforts to communicate material changes. When events outside our reasonable control require rescheduling, we may offer a replacement, rescheduled session, or another reasonable solution.</p> },
        { title: "8. Attendance", body: <p>Participants are responsible for attending scheduled sessions. Missed sessions do not automatically create a refund right. We may provide a make-up session or alternative material at our discretion. Repeated non-attendance may affect completion.</p> },
        { title: "9. Online Sessions", body: <p>You are responsible for a suitable internet connection, hardware, software, and participation environment. Articulate X is not responsible for interruptions caused by your equipment, connection, third-party platforms, or events outside our reasonable control.</p> },
        { title: "10. Training Materials", body: <><p>Materials may include slides, workbooks, frameworks, templates, worksheets, videos, recordings, exercises, assessments, and other educational content. They are for personal or authorised organisational use. Unless permitted in writing, you may not:</p><LegalList items={["Copy or reproduce substantial portions", "Sell, commercially exploit, redistribute, or publicly upload materials", "Share paid access or republish proprietary frameworks", "Create competing commercial training products from our materials", "Record or distribute sessions without permission"]}/></> },
        { title: "11. Intellectual Property", body: <p>Articulate X or its licensors own the brand, name, logo, website, course structures, frameworks, materials, presentations, written content, videos, templates, exercises, assessments, methodologies, and proprietary processes. Participation does not transfer ownership. You receive only a limited right to use materials for their intended purpose.</p> },
        { title: "12. Participant Content", body: <p>You retain ownership of content you independently create. You grant Articulate X a limited right to use submitted content as reasonably necessary to deliver programmes, review assignments, provide feedback, support participants, and improve programmes. We will not publicly use identifiable participant work, testimonials, photographs, videos, or recordings for marketing without appropriate permission or consent.</p> },
        { title: "13. Recordings", body: <p>Where sessions are recorded, we will provide appropriate notice where required. Recordings may support missed-session access, administration, quality assurance, delivery, and internal improvement. Participants must not independently record, reproduce, distribute, or publish sessions without permission.</p> },
        { title: "14. Conduct", body: <><p>Participants must behave professionally and respectfully. You must not:</p><LegalList items={["Harass, threaten, intimidate, or discriminate", "Disrupt sessions or attempt unauthorised system access", "Share another participant’s private information without permission", "Misuse materials, impersonate another person, or engage in unlawful activity", "Distribute malicious, deceptive, or harmful material"]}/><p>We may suspend or terminate participation for serious or repeated misconduct.</p></> },
        { title: "15. Corporate Training", body: <p>Corporate scope may be defined by a proposal, quotation, statement of work, purchase order, or separate agreement covering scope, fees, participants, schedule, confidentiality, cancellation, intellectual property, reporting, and payment. A specific written agreement generally governs where it conflicts with these Terms.</p> },
        { title: "16. Professional Development Disclaimer", body: <><p>Our services develop communication and professional skills, but outcomes depend on effort, experience, circumstances, implementation, and other factors outside our control. We do not guarantee employment, promotion, salary increases, revenue, sales, customers, career advancement, successful negotiations, or any specific financial or professional outcome.</p></> },
        { title: "17. Assessments", body: <p>Assessments and diagnostic exercises provide educational or developmental feedback. They are not professional certifications unless expressly identified as certification.</p> },
        { title: "18. Third-Party Services", body: <p>Payments, video conferencing, scheduling, email, analytics, advertising, forms, communication, and hosting may use third-party services. Their separate terms and policies may apply. Articulate X is not responsible for services outside our reasonable control.</p> },
        { title: "19. Website Use", body: <><p>Use the website only lawfully. You must not interfere with functionality, introduce malware, scrape content without permission, bypass security, access restricted areas, or use content for unauthorised commercial purposes.</p></> },
        { title: "20. Availability", body: <p>We aim to provide reliable access but do not guarantee uninterrupted, error-free, secure, or continuous availability. Access may be suspended for maintenance, updates, security, technical issues, operational needs, or events outside our control.</p> },
        { title: "21. Warranties", body: <p>To the maximum extent permitted by law, the website and services are provided on an “as available” basis. We do not guarantee suitability for every participant, particular outcomes, uninterrupted operation, or third-party performance. Statutory rights that cannot be excluded remain unaffected.</p> },
        { title: "22. Liability", body: <p>To the maximum extent permitted by law, Articulate X will not be liable for indirect, incidental, consequential, special, exemplary, or unforeseeable losses. Where liability cannot be excluded, it is limited to the extent permitted by applicable law.</p> },
        { title: "23. Indemnification", body: <p>To the extent permitted by law, you agree to indemnify Articulate X, its representatives, trainers, and service providers against claims or expenses arising from unlawful use, breach of these Terms, intellectual-property infringement, misuse of materials, or intentional or negligent misconduct.</p> },
        { title: "24. Suspension or Termination", body: <p>We may suspend or terminate access for material breach, abusive or unlawful conduct, material misuse, fraudulent transactions, disruption, or protection of participants, staff, systems, or the business. Termination does not automatically create a refund right.</p> },
        { title: "25. Confidentiality", body: <p>Participants should respect information reasonably understood to be confidential and must not disclose another participant’s private, professional, or commercially sensitive information without permission. Corporate programmes may include additional obligations.</p> },
        { title: "26. Testimonials", body: <p>Participants may voluntarily provide feedback or testimonials. Where identifiable testimonials are used for promotion, we will seek appropriate permission or consent where required. A participant’s experience is not a guarantee of another person’s results.</p> },
        { title: "27. Changes to Services", body: <p>We may modify, update, replace, or discontinue services. Where a material change affects an already-purchased programme, we will make reasonable efforts to provide an appropriate alternative where required.</p> },
        { title: "28. Changes to Terms", body: <p>Updated Terms will be published with a revised date. Continued use after an update may constitute acceptance to the extent permitted by law.</p> },
        { title: "29. Governing Law", body: <p>These Terms are intended to be governed by the laws of India. Subject to mandatory rights, disputes will be subject to competent courts with jurisdiction over the applicable Articulate X business entity and its registered or principal place of business.</p> },
        { title: "30. Consumer Rights", body: <p>Nothing in these Terms removes or restricts mandatory consumer rights under applicable Indian law. Articulate X will comply with relevant consumer-protection and e-commerce requirements.</p> },
        { title: "31. Entire Agreement", body: <p>These Terms, applicable programme terms, payment and refund terms, the Privacy Policy, and separately executed agreements form the applicable agreement governing use of our services.</p> },
        { title: "32. Severability", body: <p>If a provision is invalid or unenforceable, it will be modified or interpreted to the minimum extent needed where legally possible. The remaining provisions continue to apply.</p> },
        { title: "33. No Waiver", body: <p>Failure to enforce a provision does not waive our right to enforce it later.</p> },
        { title: "34. Contact", body: <p><strong>Articulate X</strong><br />Website: articulatex.in<br />Email: hello@articulatex.in<br />Business location: Mumbai, India</p> },
      ]}
    />
  );
}
